[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd websocket-server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd websocket-server && npm start"

[variables]
NODE_ENV = "production"
PORT = "3001" 